databaton:
  mode: local
  pac:
  local-server:
    proxy-type: http
    port: 9988
  remote-server:
    host: 127.0.0.1
    port: 9987
    token: databaton
  crypt:
    code: 1
    algorithm: AES/ECB/PKCS5Padding
    key: 1234567890123456


logging:
  level:
    io:
      databaton: info