databaton:
  # remote or local
  mode: local
  # tcp or udp
  protocol: tcp
  # the pac config file absolute path, the config must be a yaml file.
  # if this value is empty, then all connections will use the proxy.
  pac:
  local-server:
    # socks5 or http
    proxy-type: socks5
    port: 9988
  remote-server:
    # your remote server ip address
    host: 127.0.0.1
    port: 9987
    # make sure the local server and remote server use the same value
    token: 1234567890
  crypt:
    # see the enum class CryptType
    code: 1
    algorithm: AES/ECB/PKCS5Padding
    key: 1234567890123456


logging:
  level:
    io:
      databaton: info