// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataBatonUdpDispatchMessage.proto
// Protobuf Java Version: 4.26.1

package io.databaton.net.databaton.udp.model;

public final class DataBatonUdpDispatchMessageProto {
  private DataBatonUdpDispatchMessageProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      DataBatonUdpDispatchMessageProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataBatonUdpDispatchMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.databaton.net.databaton.model.DataBatonUdpDispatchMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string connId = 1;</code>
     * @return The connId.
     */
    java.lang.String getConnId();
    /**
     * <code>string connId = 1;</code>
     * @return The bytes for connId.
     */
    com.google.protobuf.ByteString
        getConnIdBytes();

    /**
     * <code>int32 op = 2;</code>
     * @return The op.
     */
    int getOp();

    /**
     * <code>int32 packNum = 3;</code>
     * @return The packNum.
     */
    int getPackNum();

    /**
     * <code>repeated int32 originalPackNum = 4;</code>
     * @return A list containing the originalPackNum.
     */
    java.util.List<java.lang.Integer> getOriginalPackNumList();
    /**
     * <code>repeated int32 originalPackNum = 4;</code>
     * @return The count of originalPackNum.
     */
    int getOriginalPackNumCount();
    /**
     * <code>repeated int32 originalPackNum = 4;</code>
     * @param index The index of the element to return.
     * @return The originalPackNum at the given index.
     */
    int getOriginalPackNum(int index);

    /**
     * <code>string dstHost = 5;</code>
     * @return The dstHost.
     */
    java.lang.String getDstHost();
    /**
     * <code>string dstHost = 5;</code>
     * @return The bytes for dstHost.
     */
    com.google.protobuf.ByteString
        getDstHostBytes();

    /**
     * <code>int32 dstPort = 6;</code>
     * @return The dstPort.
     */
    int getDstPort();

    /**
     * <code>string token = 7;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <code>string token = 7;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>bytes data = 8;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code io.databaton.net.databaton.model.DataBatonUdpDispatchMessage}
   */
  public static final class DataBatonUdpDispatchMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:io.databaton.net.databaton.model.DataBatonUdpDispatchMessage)
      DataBatonUdpDispatchMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        DataBatonUdpDispatchMessage.class.getName());
    }
    // Use DataBatonUdpDispatchMessage.newBuilder() to construct.
    private DataBatonUdpDispatchMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DataBatonUdpDispatchMessage() {
      connId_ = "";
      originalPackNum_ = emptyIntList();
      dstHost_ = "";
      token_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.internal_static_io_databaton_net_databaton_model_DataBatonUdpDispatchMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.internal_static_io_databaton_net_databaton_model_DataBatonUdpDispatchMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage.class, io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage.Builder.class);
    }

    public static final int CONNID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object connId_ = "";
    /**
     * <code>string connId = 1;</code>
     * @return The connId.
     */
    @java.lang.Override
    public java.lang.String getConnId() {
      java.lang.Object ref = connId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        connId_ = s;
        return s;
      }
    }
    /**
     * <code>string connId = 1;</code>
     * @return The bytes for connId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConnIdBytes() {
      java.lang.Object ref = connId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        connId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OP_FIELD_NUMBER = 2;
    private int op_ = 0;
    /**
     * <code>int32 op = 2;</code>
     * @return The op.
     */
    @java.lang.Override
    public int getOp() {
      return op_;
    }

    public static final int PACKNUM_FIELD_NUMBER = 3;
    private int packNum_ = 0;
    /**
     * <code>int32 packNum = 3;</code>
     * @return The packNum.
     */
    @java.lang.Override
    public int getPackNum() {
      return packNum_;
    }

    public static final int ORIGINALPACKNUM_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList originalPackNum_ =
        emptyIntList();
    /**
     * <code>repeated int32 originalPackNum = 4;</code>
     * @return A list containing the originalPackNum.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getOriginalPackNumList() {
      return originalPackNum_;
    }
    /**
     * <code>repeated int32 originalPackNum = 4;</code>
     * @return The count of originalPackNum.
     */
    public int getOriginalPackNumCount() {
      return originalPackNum_.size();
    }
    /**
     * <code>repeated int32 originalPackNum = 4;</code>
     * @param index The index of the element to return.
     * @return The originalPackNum at the given index.
     */
    public int getOriginalPackNum(int index) {
      return originalPackNum_.getInt(index);
    }
    private int originalPackNumMemoizedSerializedSize = -1;

    public static final int DSTHOST_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object dstHost_ = "";
    /**
     * <code>string dstHost = 5;</code>
     * @return The dstHost.
     */
    @java.lang.Override
    public java.lang.String getDstHost() {
      java.lang.Object ref = dstHost_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dstHost_ = s;
        return s;
      }
    }
    /**
     * <code>string dstHost = 5;</code>
     * @return The bytes for dstHost.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDstHostBytes() {
      java.lang.Object ref = dstHost_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dstHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DSTPORT_FIELD_NUMBER = 6;
    private int dstPort_ = 0;
    /**
     * <code>int32 dstPort = 6;</code>
     * @return The dstPort.
     */
    @java.lang.Override
    public int getDstPort() {
      return dstPort_;
    }

    public static final int TOKEN_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object token_ = "";
    /**
     * <code>string token = 7;</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 7;</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 8;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(connId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, connId_);
      }
      if (op_ != 0) {
        output.writeInt32(2, op_);
      }
      if (packNum_ != 0) {
        output.writeInt32(3, packNum_);
      }
      if (getOriginalPackNumList().size() > 0) {
        output.writeUInt32NoTag(34);
        output.writeUInt32NoTag(originalPackNumMemoizedSerializedSize);
      }
      for (int i = 0; i < originalPackNum_.size(); i++) {
        output.writeInt32NoTag(originalPackNum_.getInt(i));
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dstHost_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, dstHost_);
      }
      if (dstPort_ != 0) {
        output.writeInt32(6, dstPort_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(token_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, token_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(8, data_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(connId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, connId_);
      }
      if (op_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, op_);
      }
      if (packNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, packNum_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < originalPackNum_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(originalPackNum_.getInt(i));
        }
        size += dataSize;
        if (!getOriginalPackNumList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        originalPackNumMemoizedSerializedSize = dataSize;
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dstHost_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, dstHost_);
      }
      if (dstPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, dstPort_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(token_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, token_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage)) {
        return super.equals(obj);
      }
      io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage other = (io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage) obj;

      if (!getConnId()
          .equals(other.getConnId())) return false;
      if (getOp()
          != other.getOp()) return false;
      if (getPackNum()
          != other.getPackNum()) return false;
      if (!getOriginalPackNumList()
          .equals(other.getOriginalPackNumList())) return false;
      if (!getDstHost()
          .equals(other.getDstHost())) return false;
      if (getDstPort()
          != other.getDstPort()) return false;
      if (!getToken()
          .equals(other.getToken())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONNID_FIELD_NUMBER;
      hash = (53 * hash) + getConnId().hashCode();
      hash = (37 * hash) + OP_FIELD_NUMBER;
      hash = (53 * hash) + getOp();
      hash = (37 * hash) + PACKNUM_FIELD_NUMBER;
      hash = (53 * hash) + getPackNum();
      if (getOriginalPackNumCount() > 0) {
        hash = (37 * hash) + ORIGINALPACKNUM_FIELD_NUMBER;
        hash = (53 * hash) + getOriginalPackNumList().hashCode();
      }
      hash = (37 * hash) + DSTHOST_FIELD_NUMBER;
      hash = (53 * hash) + getDstHost().hashCode();
      hash = (37 * hash) + DSTPORT_FIELD_NUMBER;
      hash = (53 * hash) + getDstPort();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.databaton.net.databaton.model.DataBatonUdpDispatchMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.databaton.net.databaton.model.DataBatonUdpDispatchMessage)
        io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.internal_static_io_databaton_net_databaton_model_DataBatonUdpDispatchMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.internal_static_io_databaton_net_databaton_model_DataBatonUdpDispatchMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage.class, io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage.Builder.class);
      }

      // Construct using io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        connId_ = "";
        op_ = 0;
        packNum_ = 0;
        originalPackNum_ = emptyIntList();
        dstHost_ = "";
        dstPort_ = 0;
        token_ = "";
        data_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.internal_static_io_databaton_net_databaton_model_DataBatonUdpDispatchMessage_descriptor;
      }

      @java.lang.Override
      public io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage getDefaultInstanceForType() {
        return io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage.getDefaultInstance();
      }

      @java.lang.Override
      public io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage build() {
        io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage buildPartial() {
        io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage result = new io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.connId_ = connId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.op_ = op_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.packNum_ = packNum_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          originalPackNum_.makeImmutable();
          result.originalPackNum_ = originalPackNum_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.dstHost_ = dstHost_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.dstPort_ = dstPort_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.token_ = token_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.data_ = data_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage) {
          return mergeFrom((io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage other) {
        if (other == io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage.getDefaultInstance()) return this;
        if (!other.getConnId().isEmpty()) {
          connId_ = other.connId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getOp() != 0) {
          setOp(other.getOp());
        }
        if (other.getPackNum() != 0) {
          setPackNum(other.getPackNum());
        }
        if (!other.originalPackNum_.isEmpty()) {
          if (originalPackNum_.isEmpty()) {
            originalPackNum_ = other.originalPackNum_;
            originalPackNum_.makeImmutable();
            bitField0_ |= 0x00000008;
          } else {
            ensureOriginalPackNumIsMutable();
            originalPackNum_.addAll(other.originalPackNum_);
          }
          onChanged();
        }
        if (!other.getDstHost().isEmpty()) {
          dstHost_ = other.dstHost_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.getDstPort() != 0) {
          setDstPort(other.getDstPort());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                connId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                op_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                packNum_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                int v = input.readInt32();
                ensureOriginalPackNumIsMutable();
                originalPackNum_.addInt(v);
                break;
              } // case 32
              case 34: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureOriginalPackNumIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  originalPackNum_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              } // case 34
              case 42: {
                dstHost_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 48: {
                dstPort_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 58: {
                token_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                data_ = input.readBytes();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object connId_ = "";
      /**
       * <code>string connId = 1;</code>
       * @return The connId.
       */
      public java.lang.String getConnId() {
        java.lang.Object ref = connId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          connId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string connId = 1;</code>
       * @return The bytes for connId.
       */
      public com.google.protobuf.ByteString
          getConnIdBytes() {
        java.lang.Object ref = connId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          connId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string connId = 1;</code>
       * @param value The connId to set.
       * @return This builder for chaining.
       */
      public Builder setConnId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        connId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string connId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearConnId() {
        connId_ = getDefaultInstance().getConnId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string connId = 1;</code>
       * @param value The bytes for connId to set.
       * @return This builder for chaining.
       */
      public Builder setConnIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        connId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int op_ ;
      /**
       * <code>int32 op = 2;</code>
       * @return The op.
       */
      @java.lang.Override
      public int getOp() {
        return op_;
      }
      /**
       * <code>int32 op = 2;</code>
       * @param value The op to set.
       * @return This builder for chaining.
       */
      public Builder setOp(int value) {

        op_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 op = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        op_ = 0;
        onChanged();
        return this;
      }

      private int packNum_ ;
      /**
       * <code>int32 packNum = 3;</code>
       * @return The packNum.
       */
      @java.lang.Override
      public int getPackNum() {
        return packNum_;
      }
      /**
       * <code>int32 packNum = 3;</code>
       * @param value The packNum to set.
       * @return This builder for chaining.
       */
      public Builder setPackNum(int value) {

        packNum_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 packNum = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPackNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        packNum_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList originalPackNum_ = emptyIntList();
      private void ensureOriginalPackNumIsMutable() {
        if (!originalPackNum_.isModifiable()) {
          originalPackNum_ = makeMutableCopy(originalPackNum_);
        }
        bitField0_ |= 0x00000008;
      }
      /**
       * <code>repeated int32 originalPackNum = 4;</code>
       * @return A list containing the originalPackNum.
       */
      public java.util.List<java.lang.Integer>
          getOriginalPackNumList() {
        originalPackNum_.makeImmutable();
        return originalPackNum_;
      }
      /**
       * <code>repeated int32 originalPackNum = 4;</code>
       * @return The count of originalPackNum.
       */
      public int getOriginalPackNumCount() {
        return originalPackNum_.size();
      }
      /**
       * <code>repeated int32 originalPackNum = 4;</code>
       * @param index The index of the element to return.
       * @return The originalPackNum at the given index.
       */
      public int getOriginalPackNum(int index) {
        return originalPackNum_.getInt(index);
      }
      /**
       * <code>repeated int32 originalPackNum = 4;</code>
       * @param index The index to set the value at.
       * @param value The originalPackNum to set.
       * @return This builder for chaining.
       */
      public Builder setOriginalPackNum(
          int index, int value) {

        ensureOriginalPackNumIsMutable();
        originalPackNum_.setInt(index, value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 originalPackNum = 4;</code>
       * @param value The originalPackNum to add.
       * @return This builder for chaining.
       */
      public Builder addOriginalPackNum(int value) {

        ensureOriginalPackNumIsMutable();
        originalPackNum_.addInt(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 originalPackNum = 4;</code>
       * @param values The originalPackNum to add.
       * @return This builder for chaining.
       */
      public Builder addAllOriginalPackNum(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureOriginalPackNumIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, originalPackNum_);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 originalPackNum = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearOriginalPackNum() {
        originalPackNum_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private java.lang.Object dstHost_ = "";
      /**
       * <code>string dstHost = 5;</code>
       * @return The dstHost.
       */
      public java.lang.String getDstHost() {
        java.lang.Object ref = dstHost_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dstHost_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dstHost = 5;</code>
       * @return The bytes for dstHost.
       */
      public com.google.protobuf.ByteString
          getDstHostBytes() {
        java.lang.Object ref = dstHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dstHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dstHost = 5;</code>
       * @param value The dstHost to set.
       * @return This builder for chaining.
       */
      public Builder setDstHost(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        dstHost_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string dstHost = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDstHost() {
        dstHost_ = getDefaultInstance().getDstHost();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string dstHost = 5;</code>
       * @param value The bytes for dstHost to set.
       * @return This builder for chaining.
       */
      public Builder setDstHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        dstHost_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private int dstPort_ ;
      /**
       * <code>int32 dstPort = 6;</code>
       * @return The dstPort.
       */
      @java.lang.Override
      public int getDstPort() {
        return dstPort_;
      }
      /**
       * <code>int32 dstPort = 6;</code>
       * @param value The dstPort to set.
       * @return This builder for chaining.
       */
      public Builder setDstPort(int value) {

        dstPort_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dstPort = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDstPort() {
        bitField0_ = (bitField0_ & ~0x00000020);
        dstPort_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 7;</code>
       * @return The token.
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 7;</code>
       * @return The bytes for token.
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 7;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        token_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        token_ = getDefaultInstance().getToken();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string token = 7;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        token_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 8;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 8;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000080);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:io.databaton.net.databaton.model.DataBatonUdpDispatchMessage)
    }

    // @@protoc_insertion_point(class_scope:io.databaton.net.databaton.model.DataBatonUdpDispatchMessage)
    private static final io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage();
    }

    public static io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataBatonUdpDispatchMessage>
        PARSER = new com.google.protobuf.AbstractParser<DataBatonUdpDispatchMessage>() {
      @java.lang.Override
      public DataBatonUdpDispatchMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DataBatonUdpDispatchMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataBatonUdpDispatchMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.databaton.net.databaton.udp.model.DataBatonUdpDispatchMessageProto.DataBatonUdpDispatchMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_databaton_net_databaton_model_DataBatonUdpDispatchMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_databaton_net_databaton_model_DataBatonUdpDispatchMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!DataBatonUdpDispatchMessage.proto\022 io." +
      "databaton.net.databaton.model\"\242\001\n\033DataBa" +
      "tonUdpDispatchMessage\022\016\n\006connId\030\001 \001(\t\022\n\n" +
      "\002op\030\002 \001(\005\022\017\n\007packNum\030\003 \001(\005\022\027\n\017originalPa" +
      "ckNum\030\004 \003(\005\022\017\n\007dstHost\030\005 \001(\t\022\017\n\007dstPort\030" +
      "\006 \001(\005\022\r\n\005token\030\007 \001(\t\022\014\n\004data\030\010 \001(\014BH\n$io" +
      ".databaton.net.databaton.udp.modelB Data" +
      "BatonUdpDispatchMessageProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_databaton_net_databaton_model_DataBatonUdpDispatchMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_databaton_net_databaton_model_DataBatonUdpDispatchMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_databaton_net_databaton_model_DataBatonUdpDispatchMessage_descriptor,
        new java.lang.String[] { "ConnId", "Op", "PackNum", "OriginalPackNum", "DstHost", "DstPort", "Token", "Data", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
