// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataBatonLoginMessage.proto
// Protobuf Java Version: 4.26.1

package io.databaton.net.databaton.model;

public final class DataBatonLoginMessageProto {
  private DataBatonLoginMessageProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      DataBatonLoginMessageProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataBatonLoginMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.databaton.net.databaton.model.DataBatonLoginMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string username = 1;</code>
     * @return The username.
     */
    java.lang.String getUsername();
    /**
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>string dstHost = 3;</code>
     * @return The dstHost.
     */
    java.lang.String getDstHost();
    /**
     * <code>string dstHost = 3;</code>
     * @return The bytes for dstHost.
     */
    com.google.protobuf.ByteString
        getDstHostBytes();

    /**
     * <code>int32 dstPort = 4;</code>
     * @return The dstPort.
     */
    int getDstPort();

    /**
     * <code>bytes data = 5;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code io.databaton.net.databaton.model.DataBatonLoginMessage}
   */
  public static final class DataBatonLoginMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:io.databaton.net.databaton.model.DataBatonLoginMessage)
      DataBatonLoginMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        DataBatonLoginMessage.class.getName());
    }
    // Use DataBatonLoginMessage.newBuilder() to construct.
    private DataBatonLoginMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DataBatonLoginMessage() {
      username_ = "";
      password_ = "";
      dstHost_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.databaton.net.databaton.model.DataBatonLoginMessageProto.internal_static_io_databaton_net_databaton_model_DataBatonLoginMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.databaton.net.databaton.model.DataBatonLoginMessageProto.internal_static_io_databaton_net_databaton_model_DataBatonLoginMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage.class, io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage.Builder.class);
    }

    public static final int USERNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object username_ = "";
    /**
     * <code>string username = 1;</code>
     * @return The username.
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object password_ = "";
    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    @java.lang.Override
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DSTHOST_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object dstHost_ = "";
    /**
     * <code>string dstHost = 3;</code>
     * @return The dstHost.
     */
    @java.lang.Override
    public java.lang.String getDstHost() {
      java.lang.Object ref = dstHost_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dstHost_ = s;
        return s;
      }
    }
    /**
     * <code>string dstHost = 3;</code>
     * @return The bytes for dstHost.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDstHostBytes() {
      java.lang.Object ref = dstHost_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dstHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DSTPORT_FIELD_NUMBER = 4;
    private int dstPort_ = 0;
    /**
     * <code>int32 dstPort = 4;</code>
     * @return The dstPort.
     */
    @java.lang.Override
    public int getDstPort() {
      return dstPort_;
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 5;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(username_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, username_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(password_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, password_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dstHost_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, dstHost_);
      }
      if (dstPort_ != 0) {
        output.writeInt32(4, dstPort_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(5, data_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(username_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, username_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(password_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, password_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dstHost_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, dstHost_);
      }
      if (dstPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, dstPort_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage)) {
        return super.equals(obj);
      }
      io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage other = (io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage) obj;

      if (!getUsername()
          .equals(other.getUsername())) return false;
      if (!getPassword()
          .equals(other.getPassword())) return false;
      if (!getDstHost()
          .equals(other.getDstHost())) return false;
      if (getDstPort()
          != other.getDstPort()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + DSTHOST_FIELD_NUMBER;
      hash = (53 * hash) + getDstHost().hashCode();
      hash = (37 * hash) + DSTPORT_FIELD_NUMBER;
      hash = (53 * hash) + getDstPort();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.databaton.net.databaton.model.DataBatonLoginMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.databaton.net.databaton.model.DataBatonLoginMessage)
        io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.databaton.net.databaton.model.DataBatonLoginMessageProto.internal_static_io_databaton_net_databaton_model_DataBatonLoginMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.databaton.net.databaton.model.DataBatonLoginMessageProto.internal_static_io_databaton_net_databaton_model_DataBatonLoginMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage.class, io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage.Builder.class);
      }

      // Construct using io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        username_ = "";
        password_ = "";
        dstHost_ = "";
        dstPort_ = 0;
        data_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.databaton.net.databaton.model.DataBatonLoginMessageProto.internal_static_io_databaton_net_databaton_model_DataBatonLoginMessage_descriptor;
      }

      @java.lang.Override
      public io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage getDefaultInstanceForType() {
        return io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage.getDefaultInstance();
      }

      @java.lang.Override
      public io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage build() {
        io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage buildPartial() {
        io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage result = new io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.username_ = username_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.password_ = password_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.dstHost_ = dstHost_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.dstPort_ = dstPort_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.data_ = data_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage) {
          return mergeFrom((io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage other) {
        if (other == io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage.getDefaultInstance()) return this;
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getDstHost().isEmpty()) {
          dstHost_ = other.dstHost_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getDstPort() != 0) {
          setDstPort(other.getDstPort());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                username_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                password_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                dstHost_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                dstPort_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                data_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object username_ = "";
      /**
       * <code>string username = 1;</code>
       * @return The username.
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string username = 1;</code>
       * @return The bytes for username.
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string username = 1;</code>
       * @param value The username to set.
       * @return This builder for chaining.
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        username_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string username = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsername() {
        username_ = getDefaultInstance().getUsername();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string username = 1;</code>
       * @param value The bytes for username to set.
       * @return This builder for chaining.
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        username_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 2;</code>
       * @return The password.
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       * @return The bytes for password.
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        password_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        password_ = getDefaultInstance().getPassword();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        password_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object dstHost_ = "";
      /**
       * <code>string dstHost = 3;</code>
       * @return The dstHost.
       */
      public java.lang.String getDstHost() {
        java.lang.Object ref = dstHost_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dstHost_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dstHost = 3;</code>
       * @return The bytes for dstHost.
       */
      public com.google.protobuf.ByteString
          getDstHostBytes() {
        java.lang.Object ref = dstHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dstHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dstHost = 3;</code>
       * @param value The dstHost to set.
       * @return This builder for chaining.
       */
      public Builder setDstHost(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        dstHost_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string dstHost = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDstHost() {
        dstHost_ = getDefaultInstance().getDstHost();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string dstHost = 3;</code>
       * @param value The bytes for dstHost to set.
       * @return This builder for chaining.
       */
      public Builder setDstHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        dstHost_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int dstPort_ ;
      /**
       * <code>int32 dstPort = 4;</code>
       * @return The dstPort.
       */
      @java.lang.Override
      public int getDstPort() {
        return dstPort_;
      }
      /**
       * <code>int32 dstPort = 4;</code>
       * @param value The dstPort to set.
       * @return This builder for chaining.
       */
      public Builder setDstPort(int value) {

        dstPort_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dstPort = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDstPort() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dstPort_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 5;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 5;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000010);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:io.databaton.net.databaton.model.DataBatonLoginMessage)
    }

    // @@protoc_insertion_point(class_scope:io.databaton.net.databaton.model.DataBatonLoginMessage)
    private static final io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage();
    }

    public static io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataBatonLoginMessage>
        PARSER = new com.google.protobuf.AbstractParser<DataBatonLoginMessage>() {
      @java.lang.Override
      public DataBatonLoginMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DataBatonLoginMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataBatonLoginMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.databaton.net.databaton.model.DataBatonLoginMessageProto.DataBatonLoginMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_databaton_net_databaton_model_DataBatonLoginMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_databaton_net_databaton_model_DataBatonLoginMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033DataBatonLoginMessage.proto\022 io.databa" +
      "ton.net.databaton.model\"k\n\025DataBatonLogi" +
      "nMessage\022\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002" +
      " \001(\t\022\017\n\007dstHost\030\003 \001(\t\022\017\n\007dstPort\030\004 \001(\005\022\014" +
      "\n\004data\030\005 \001(\014B>\n io.databaton.net.databat" +
      "on.modelB\032DataBatonLoginMessageProtob\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_databaton_net_databaton_model_DataBatonLoginMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_databaton_net_databaton_model_DataBatonLoginMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_databaton_net_databaton_model_DataBatonLoginMessage_descriptor,
        new java.lang.String[] { "Username", "Password", "DstHost", "DstPort", "Data", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
